// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbscbclhzzcklncilagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ic2NiY2xoenpja2xuY2lsYWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDQ4NjYsImV4cCI6MjA3MTE4MDg2Nn0.H0K0fYBlQp9aG6KbbG8DoxPyF7bwS7s3Gb4dhIFMufk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});